name: ssh-mitm # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.5.7' # just for humans, typically '1.2+git' or '1.3.2'
summary: ssh mitm server for security audits # 79 char long summary
description: |
  ssh mitm server for security audits supporting 
  public key authentication, session hijacking and file manipulation

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: [amd64]

parts:
  ssh-mitm:
    # See 'snapcraft plugins'
    plugin: python
    python-packages:
      - ssh-mitm
apps:
  ssh-mitm:
    command: usr/bin/python3 $SNAP/bin/ssh-mitm
    plugs:
      - home
      - network
      - network-bind
